/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(project(":flightSelection-frontend"))
    // This dependency is used by the application.
    implementation(libs.guava)    
}

tasks.register("cleanNestJs") {
    onlyIf { project.hasProperty("withNestJs") }    
    doLast {
        delete("src/nestjs/node_modules")
        delete("src/nestjs/dist")
    }    
}

tasks.register<Exec>("installNestJs") {
    onlyIf { project.hasProperty("withNestJs") }
    logger.info("Task buildNestJs - npm install")
    workingDir("src/nestjs")
    if (System.getProperty("os.name").uppercase().contains("WINDOWS")) {
        commandLine("npm.cmd", "install")
    } else {
        commandLine("npm", "install")
    }
    dependsOn(tasks.named("cleanNestJs"))
}

tasks.register<Exec>("buildNestJs") {
   onlyIf { project.hasProperty("withNestJs") }
    logger.info("Task buildNestJs - npm run build")
    workingDir("src/nestjs")    
    if (System.getProperty("os.name").uppercase().contains("WINDOWS")) {
        commandLine("npm.cmd", "run", "build")
    } else {
        commandLine("npm", "run", "build")
    }
    dependsOn(tasks.named("cleanNestJs"), tasks.named("installNestJs"))
}

tasks.named("build") {
    dependsOn(tasks.named("buildNestJs"))
}

// Ensure backend tasks wait for frontend

tasks.named("processResources") {
	dependsOn(":flightSelection-frontend:buildAngular")
}

tasks.named("classes") {
	dependsOn(":flightSelection-frontend:buildAngular")
}

// The application plugin doesn't provide a `bootJar` task; use `jar` instead
tasks.named("jar") {
    dependsOn(":flightSelection-frontend:buildAngular")
}