/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
}

task("cleanNestJs") {
    if(project.hasProperty("withNestJs")) {
        logger.info("Task cleanAngular")
        delete("src/angular/node_modules")
    }
}

task("buildNestJs") {
    if (project.hasProperty("withNestJs")) {
        exec {
            logger.info("Task buildNestJs - npm install")
            workingDir("src/nestjs")
            if (System.getProperty("os.name").uppercase().contains("WINDOWS")) {
                commandLine("npm.cmd", "install")
            } else {
                commandLine("npm", "install")
            }
        }
        exec {
            logger.info("Task buildNestJs - npm run build")
            workingDir("src/nestjs")
            if (System.getProperty("os.name").uppercase().contains("WINDOWS")) {
                commandLine("npm.cmd", "run", "build")
            } else {
                commandLine("npm", "run", "build")
            }
        }
    }
}