/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

import com.github.gradle.node.npm.task.NpmTask

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.github.node-gradle.node") version "7.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(project(":flightSelection-frontend"))
    // This dependency is used by the application.
    implementation(libs.guava)    
}

node {
    version = "22.16.0"
    npmVersion = "10.9.2"
    download = true
    nodeProjectDir = file("${project.projectDir}/src/nestjs")
}

tasks.register("cleanNestJs") {
    onlyIf { project.hasProperty("withNestJs") }    
    doLast {
        delete("src/nestjs/node_modules")
        delete("src/nestjs/dist")
    }    
}

tasks.register<NpmTask>("installNestJs") {
    onlyIf { project.hasProperty("withNestJs") }
    args.set(listOf("install"))
    dependsOn("nodeSetup", "npmSetup")
    dependsOn("cleanNestJs")
}

tasks.register<NpmTask>("buildNestJs") {
    onlyIf { project.hasProperty("withNestJs") }
    args.set(listOf("run", "build"))
    dependsOn("cleanNestJs", "installNestJs")
}

tasks.named("build") {
    dependsOn(tasks.named("buildNestJs"))
}

// Ensure backend tasks wait for frontend

tasks.named("processResources") {
	dependsOn(":flightSelection-frontend:buildAngular")
}

tasks.named("classes") {
	dependsOn(":flightSelection-frontend:buildAngular")
}

// The application plugin doesn't provide a `bootJar` task; use `jar` instead
tasks.named("jar") {
    dependsOn(":flightSelection-frontend:buildAngular")
}