/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

import com.github.gradle.node.npm.task.NpmTask

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.github.node-gradle.node") version "7.1.0"
}

group = "de.xxx"
version = "0.0.1-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

node {
    version = "24.16.0"
    npmVersion = "11.13.0"
    download = true // Lädt Node/NPM automatisch herunter
    nodeProjectDir = file("${project.projectDir}/src/angular")
}

tasks.register("cleanAngular") {
    onlyIf { project.hasProperty("withAngular") }
    doLast {
        println("Task cleanAngular")
        delete("src/angular/node_modules")
    }
}

tasks.register("cleanDist") {
    onlyIf { project.hasProperty("withAngular") }
    doLast {
        delete("src/angular/dist")
    }
}

tasks.register("createDist") {
    onlyIf { project.hasProperty("withAngular") }
    doLast {
        mkdir("src/angular/dist")
    }
}

tasks.register<NpmTask>("npmInstallCustom") {
    onlyIf { project.hasProperty("withAngular") }

    args.set(listOf("install"))

    dependsOn("nodeSetup", "npmSetup")
    dependsOn("cleanAngular")
}

tasks.register<NpmTask>("buildAngular") {
    onlyIf {
        project.hasProperty("withAngular")
    }

    args.set(listOf("run", "build"))

    dependsOn("npmInstall", "cleanDist", "createDist")
}

tasks.register<NpmTask>("testAngular") {
    onlyIf {
        project.hasProperty("withAngular")
    }
    if (project.hasProperty("useChromium")) {
        args.set(listOf("run", "test-chromium"))
    } else {
        args.set(listOf("run", "test"))
    }

    dependsOn("npmBuild")
}

// Make sure the main build task depends on buildAngular
tasks.named("build") {
    dependsOn(tasks.named("buildAngular"))
}