/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

group = "de.xxx"
version = "0.0.1-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

tasks.register("cleanAngular") {
    onlyIf { project.hasProperty("withAngular") }
    doLast {
        println("Task cleanAngular")
        delete("src/angular/node_modules")
    }
}

tasks.register("cleanDist") {
    onlyIf { project.hasProperty("withAngular") }
    doLast {
        delete("src/angular/dist")
    }
}

tasks.register("createDist") {
    onlyIf { project.hasProperty("withAngular") }
    doLast {
        mkdir("src/angular/dist")
    }
}

tasks.register<Exec>("npmInstall") {
    onlyIf { project.hasProperty("withAngular") }
    workingDir = file("src/angular")
    if (System.getProperty("os.name").uppercase().contains("WINDOWS")) {
        commandLine("npm.cmd", "install")
    } else {
        commandLine("npm", "install")
    }
    dependsOn(tasks.named("cleanAngular"))
}

tasks.register<Exec>("npmBuild") {
    onlyIf { project.hasProperty("withAngular") }
    workingDir = file("src/angular")
    if (System.getProperty("os.name").uppercase().contains("WINDOWS")) {
        commandLine("npm.cmd", "run", "build")
    } else {
        commandLine("npm", "run", "build")
    }
    dependsOn(tasks.named("npmInstall"), tasks.named("cleanDist"), tasks.named("createDist"))
}

tasks.register<Exec>("testAngular") {
    onlyIf { project.hasProperty("withAngular") }
    workingDir = file("src/angular")
    if (System.getProperty("os.name").uppercase().contains("WINDOWS")) {
        commandLine("npm.cmd", "run", "test")
    } else {
        if (project.hasProperty("useChromium")) {
            commandLine("npm", "run", "test-chromium")
        } else {
            commandLine("npm", "run", "test")
        }
    }
    dependsOn(tasks.named("npmInstall"))
}

tasks.register("buildAngular") {
    dependsOn(tasks.named("npmBuild"), tasks.named("testAngular"))
}

// Make sure the main build task depends on buildAngular
tasks.named("build") {
    dependsOn(tasks.named("buildAngular"))
}